# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 15:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer', '0005_auto_20160618_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='name', verbose_name='Slug')),
                ('icon', models.CharField(blank=True, default='info_outline', max_length=32, null=True, verbose_name='Category Icon')),
                ('icon_type', models.CharField(blank=True, default='materialize', max_length=32, null=True, verbose_name='Icon Library to Use')),
                ('badge_color', models.CharField(blank=True, default='red', max_length=32, null=True, verbose_name='Category Badge Color')),
            ],
            options={
                'verbose_name': 'Classifieds Category',
                'verbose_name_plural': 'Classifieds Categories',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'New'), (2, 'Active'), (3, 'Disabled'), (4, 'Outdated'), (5, 'Completed'), (99, 'Deleted')], default=1, help_text='Classifieds Status', null=True, verbose_name='Status')),
                ('classified_type', models.SmallIntegerField(blank=True, choices=[(1, 'Classified for donation'), (2, 'Classified for demanding')], default=1, null=True, verbose_name='Classified Type')),
                ('active_till', models.DateField(blank=True, null=True, verbose_name='Active Till')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifieds', to='classifieds.Category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
                'ordering': ['modified', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('classified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.Donation', verbose_name='Classified Image')),
                ('file', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='classified_image', to='filer.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='City')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Location object')),
                ('country', models.CharField(max_length=64, verbose_name='Country')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifieds', to='classifieds.Place', verbose_name='Place'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifieds', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
